GETSP _MEMORY_SIZE SWAP SAVE 
_main CALL 
GETRV HALT  
:_MEMORY_SIZE 0 
:_PROGRAM_SIZE PROGRAM_SIZE 
:_out 
GETFP GETSP SETFP 

GETFP 2 ADD LOAD OUT 

:__EPILOGUE2 
GETFP SETSP SETFP 
GETSP 0 ADD 
SWAP SAVE 
GETSP -1 ADD SETSP 
RET 

:_main 
GETFP GETSP SETFP 
GETSP 1 SUB SETSP 

GETFP 1 SUB 14 SAVE GETFP 1 SUB LOAD _out CALL GETRV 
DROP GETFP 1 SUB LOAD SETRV __EPILOGUE3 JMP 

:__EPILOGUE3 
GETFP SETSP SETFP 
GETSP 1 ADD 
SWAP SAVE 
GETSP 0 ADD SETSP 
RET 


